### ISSUE TITLE
Do you know to tool Joi?

### ISSUE THREAD

**Issue by ffekirnew** [AnaniyaT/debt-tracker#4]
You can greatly improve your secrets and how you manage your constants by first validating them, as well.
https://github.com/AnaniyaT/debt-tracker/blob/ba92a3425eb112e00ef23260e957f648aa8511f0/src/middlewares/auth.middleware.ts#L14

**Comment by AnaniyaT** [comment]
Haven't used it before but it looks interesting. I'll try to use it. Thanks
